language: objective-c
osx_image: xcode7.3
cache: cocoapods
before_install:
  - gem install cocoapods
  - pod install --project-directory=Example
script:
  - set -o pipefail && xcodebuild test -workspace Example/CassowarySwift.xcworkspace -scheme CassowarySwift-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint
